name: kind and minikube clusters create

on:
  push:
    branches: [master]

jobs:
  kind:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.info.outputs.info }}
      output2: ${{ steps.time.outputs.time }}

    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      
      - name: Testing kind-cluster and get info
        run: |
          echo "kube version:" $(kubectl version --short) >> report.log
          kubectl get pods -n kube-system >> report.log
                           

      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
 


  #minikube:
  #  needs: kind
  #  runs-on: ubuntu-latest
    
  #  steps:
    
  #  - uses: actions/checkout@v2
    
  #  - name: Start minikube
  #    uses: medyagh/setup-minikube@master
    
  #  - name: Try the cluster !
  #    run: kubectl get pods -A
