name: kind and minikube clusters create

on:
  push:
    branches: [master]

env:
      start_kind: var_start_kind_sec
      report: report.log

jobs:
  kind:
    runs-on: ubuntu-latest
    outputs:
      out1: ${{ steps.start1.outputs.start1 }}
           
    steps:
      - name: job's start time
        id: start1
        run: echo "start1=$(date '+%s')" >> $GITHUB_OUTPUT

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      
      - name: Testing cluster and get info
        run: |
          echo "kube version:\n $(kubectl version --short)" >>  ${{ env.report }}
          echo "amount nodes: $(kubectl get nodes | grep -c 'Ready') \n" >> ${{ env.report }}
          echo "time for start cluster: $(($(date '+%s')-${{ steps.start1.outputs.start1 }})) seconds" >> ${{ env.report }}
     
      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.report }}



  minikube:
    needs: kind
    runs-on: ubuntu-latest
    
    outputs:
        out2: ${{ steps.start2.outputs.start2 }}
    
    steps:

      - name: job's start time
        id: start2
        run: echo "start2=$(date '+%s')" >> $GITHUB_OUTPUT
    
      - name: Start minikube
        uses: medyagh/setup-minikube@master
    
      - name: Testing cluster and get info
        run: |
          echo "\n kube version:\n $(kubectl version --short)" >>  ${{ env.report }}
          echo "amount nodes: $(kubectl get nodes | grep -c 'Ready') \n" >> ${{ env.report }}
          echo "time for start cluster: $(($(date '+%s')-${{ steps.start2.outputs.start2 }})) seconds" >> ${{ env.report }}

      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.report }}
